services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: polling_backend_dev
    environment:
      - TESTER_PASSWORD=test
      - TESTER1_PASSWORD=test1
      - TESTER2_PASSWORD=test2
    ports:
      - "8000:8000"
    volumes:
      - ./sqlite_data:/app/data
      - ./backend:/app        # hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build           # stop at build stage
    container_name: polling_frontend_dev
    command: npm run dev -- --host
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped